settings:
  server-id: '00000000'
  channel: 'test'
  username: 'username'
  email: 'email@example.com'
  password: 'password'
  debug: false
  templates:
    discord:
      chat_message: '<%u> %m'
      player_join: '%u joined the server'
      player_leave: '%u left the server'
    minecraft:
      chat_message: '<%u&b(discord)&r> %m'
